const products = [
  {
    _id: "  01",
    title: "تیرآهن IPE 12 - ذوب آهن",
    producer: "فولاد آریا",
    supplier: "پلاک ۲۶",
    price: "16.150",
    updateDate: "۱۴۰۲/۲/۱",
    analysis: "A3",
    loading: "کارخانه",
    state: "شاخه ۱۲ متری",
    size: 18,
    type: "شاخه آجدار",
    unit: "کیلوگرم",
    liked: "۳۲۵",
    tax: "17.604",
  },
  {
    _id: "  01",
    title: "تیرآهن IPE 12 - ذوب آهن",
    producer: "فولاد آریا",
    supplier: "پلاک ۲۶",
    price: "16.150",
    updateDate: "۱۴۰۲/۲/۱",
    analysis: "A3",
    loading: "کارخانه",
    state: "شاخه ۱۲ متری",
    size: 18,
    type: "شاخه آجدار",
    unit: "کیلوگرم",
    liked: "۳۲۵",
    tax: "17.604",
  },
  {
    _id: "  01",
    title: "تیرآهن IPE 12 - ذوب آهن",
    producer: "فولاد آریا",
    supplier: "پلاک ۲۶",
    price: "16.150",
    updateDate: "۱۴۰۲/۲/۱",
    analysis: "A3",
    loading: "کارخانه",
    state: "شاخه ۱۲ متری",
    size: 18,
    type: "شاخه آجدار",
    unit: "کیلوگرم",
    liked: "۳۲۵",
    tax: "17.604",
  },
  {
    _id: "  01",
    title: "تیرآهن IPE 12 - ذوب آهن",
    producer: "فولاد آریا",
    supplier: "پلاک ۲۶",
    price: "16.150",
    updateDate: "۱۴۰۲/۲/۱",
    analysis: "A3",
    loading: "کارخانه",
    state: "شاخه ۱۲ متری",
    size: 18,
    type: "شاخه آجدار",
    unit: "کیلوگرم",
    liked: "۳۲۵",
    tax: "17.604",
  },
  {
    _id: "  01",
    title: "تیرآهن IPE 12 - ذوب آهن",
    producer: "فولاد آریا",
    supplier: "پلاک ۲۶",
    price: "16.150",
    updateDate: "۱۴۰۲/۲/۱",
    analysis: "A3",
    loading: "کارخانه",
    state: "شاخه ۱۲ متری",
    size: 18,
    type: "شاخه آجدار",
    unit: "کیلوگرم",
    liked: "۳۲۵",
    tax: "17.604",
  },
];

export function getProducts() {
  return products;
}
